- hosts: localhost
  vars:
    home: /host/home
    zshrc: "{{ home  }}/.zshrc"
    gitconfig: "{{ home }}/.gitconfig"

  tasks:
    - name: add preload of asdf and asdf completions
      lineinfile:
        path: "{{ zshrc }}"
        state: present
        line: . $HOME/.asdf/asdf.sh

    - name: set plugins for zsh
      lineinfile:
        path: "{{ zshrc }}"
        regexp: '^plugins='
        state: present
        line: plugins=(git docker)

    - name: set emacs as default editor in gitconfig
      blockinfile:
        path: "{{ gitconfig }}"
        state: present
        block: |
          [core]
             editor = emacs

    - name: set format for git log
      blockinfile:
        path: "{{ gitconfig }}"
        state: present
        block: |
          [pretty]
              my = format:%C(yellow)%h%C(reset) | %C(dim green)%cd%C(reset) | %C(green)%cr%C(reset) | %C(cyan)%s%C(red)%d%C(red)%C(reset) %C(blue)[%an]%C(reset)
          [format]
              pretty = my
